services:
  - type: worker
    name: yoinker
    plan: free
    runtime: go
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: ./yoinker
    envVars:
      - key: RUN_PERIOD
        sync: false
      - key: WALLET
        sync: false
      - key: BASE_RPC
        sync: false
